baseurl = "https://af7nk.com/"
languageCode = "en-us"
title = "AF7NK"
theme = "blueberry-detox"

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true

[author]
  name = "Dustin Brewer"